### ISSUE TITLE
Breaks Ember Inspector

### ISSUE THREAD

**Issue by alexgb** [pzuraq/liquid-wormhole#6] opened 2016-05-04 22:54 UTC
It appears that appending a component to the application rootElement as done in the [liquid-target-container initializer](https://github.com/pzuraq/liquid-wormhole/blob/master/addon/instance-initializers/browser/liquid-target-container.js#L10) results in a broken view tree in the Ember Inspector. Instead of seeing the full application tree, I'm seeing a tree where the root node is the liquid-target-container component.

I've verified this on a fresh Ember 2.4.5 app with liquid-wormhole 1.1.0 and version 1.10.0 of the Ember Inspector.

**Comment by kevinansfield** [comment] 2016-06-02 15:49
This has been the case since I implemented `liquid-tether` based modals months ago in Ghost too:

![screen shot 2016-06-02 at 16 47 28](https://cloud.githubusercontent.com/assets/415/15751367/c6e5f61a-28e1-11e6-9e78-dad4f72d7ae0.png)

Not sure if it's a `liquid-tether`, `liquid-wormhole`, or Ember Inspector issue but some pointers in where to start looking would be useful.

**Comment by pzuraq** [comment] 2016-06-27 17:12
Sorry I didn't respond more quickly, didn't have notifications set up for this repo.

My best guess is that Ember Inspector expects a single `ember-view` at the top level and follows that downwards. I'm going to dive in and see if I can't figure out a way to fix it there, as changing the place that liquidTargetContainer appends itself could break some apps.

**Comment by brendanoh** [comment] 2016-08-15 04:49
Are they any updates on this?

I love this addon but breaking the inspector makes debugging components much harder.

**Comment by pzuraq** [comment] 2016-08-16 17:30
I've been pretty busy over the past few months so haven't had a chance to really dive in and look at it. I have some free time coming up over the next few weeks, so I'll try to get to it then.

**Comment by pzuraq** [comment] 2016-09-20 18:00
This issue has been fixed in the beta for v2. I'll be backporting a few more fixes to a v1 branch, as there are a lot of breaking changes in the API, but I'm not sure if this one will be able to make it in as it changes the positioning logic for the default liquid target (it is appended after the app instead of before it). It technically could cause regressions, breaking semver, but I'm not sure anyone's apps would notice, so it may happen.

**Comment by brendanoh** [comment] 2016-09-20 19:18
Is the beta for v2 stable @pzuraq ? I see the branch but not any beta releases.

**Comment by pzuraq** [comment] 2016-09-20 19:22
I published the beta to NPM, and just pushed the tag. It is stable, but I'm still updating the tests and documentation for the new API.

**Comment by pzuraq** [comment] 2016-09-20 19:51
@brendanoh [here's a list of some of the major breaking changes](https://github.com/pzuraq/liquid-wormhole/releases/tag/v2.0.0-beta.1) if you'd like to start testing it out now. I'll be compiling a more thorough upgrade guide soon.

**Closed** 2016-10-25 00:56 UTC
